filebeat.inputs:
- type: mqtt
  hosts:
    - tcp://localhost:1883
  topics:
    - cfeed
    - ctime
  username: user
  password: password
  client_id: logger

output.logstash:
  hosts: [ "localhost:5044" ]
